[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.23"
optimizer = true
optimizer_runs = 200

[profile.remappings]
"@openzeppelin/contracts-upgradeable/" = "lib/openzeppelin-contracts-upgradeable/contracts/"
"@openzeppelin/contracts/" = "lib/openzeppelin-contracts/contracts/"
"@aragon/osx-commons-contracts/" = "lib/osx-commons/contracts/"
"@pythnetwork/entropy-sdk-solidity/" = "node_modules/@pythnetwork/entropy-sdk-solidity/"
